# Generated by Django 4.0.3 on 2022-11-04 18:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_date', models.DateField(verbose_name='Event date')),
                ('intro', models.CharField(default='', max_length=250)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('details', wagtail.fields.RichTextField(blank=True)),
                ('player_limit', models.IntegerField(default=0)),
                ('monster_limit', models.IntegerField(default=0)),
                ('player_cost', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Player cost')),
                ('monster_cost', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Monster cost')),
                ('player_catering_cost', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Player catering cost')),
                ('monster_catering_cost', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Monster catering cost')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('lt_player_id', models.CharField(blank=True, help_text='Required if you have an existing Lorien Trust character (otherwise no blue gold for you!)', max_length=15, null=True)),
                ('player_type', models.CharField(choices=[('PL', 'Player'), ('MN', 'Monster'), ('ST', 'Staff')], default='PL', max_length=2)),
                ('character_name', models.CharField(max_length=255)),
                ('character_faction', models.CharField(blank=True, choices=[('B', 'Bears'), ('D', 'Dragons'), ('G', 'Gryphons'), ('H', 'Harts'), ('J', 'Jackals'), ('L', 'Lions'), ('T', 'Tarantulas'), ('U', 'Unicorns'), ('V', 'Vipers'), ('W', 'Wolves')], max_length=1, null=True)),
                ('is_catering', models.BooleanField(default=False, verbose_name='YES, I want food!')),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('home_address', models.TextField(blank=True)),
                ('medical_information', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
