# Generated by Django 4.0.3 on 2022-11-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventbooking_has_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='character_faction',
            field=models.CharField(blank=True, choices=[('B', 'Bears'), ('D', 'Dragons'), ('G', 'Gryphons'), ('H', 'Harts'), ('J', 'Jackals'), ('L', 'Lions'), ('T', 'Tarantulas'), ('U', 'Unicorns'), ('V', 'Vipers'), ('W', 'Wolves')], max_length=1, null=True, verbose_name='Faction'),
        ),
    ]
