# Generated by Django 4.0.3 on 2022-11-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventpage_catering_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='catering_contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='catering_name',
            field=models.CharField(max_length=250),
        ),
    ]
