# Generated by Django 4.1.13 on 2024-03-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventpage_catering_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_types', models.CharField(choices=[('PL', 'Player'), ('MN', 'Monster'), ('ST', 'Staff'), ('A', 'All')], max_length=8)),
                ('email_content', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventpage')),
            ],
        ),
    ]
