# Generated by Django 4.0.3 on 2023-01-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footertextsnippet',
            options={'ordering': ['display_order'], 'verbose_name': 'footer text', 'verbose_name_plural': 'footer texts'},
        ),
    ]
