# Generated by Django 4.0.3 on 2023-01-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_admindata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admindata',
            options={'verbose_name': 'Admin Resource'},
        ),
    ]
